[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
student_intro = "DW5zGn3TJdt1kPUrWnSuqjq8yG1iG83vDS3MpeCxfiH4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
